### ISSUE TITLE
bugs:)

### ISSUE THREAD

**Issue by koo5** [awto/fnotation#1]
This is the best i found, but some translations are incorrect. 
for example,
```
process_request_depreciation_new :-
	request_data(D),
	doc_value(D, depr_ui:depreciation_queries, _),

	(	maplist(process_depreciation_asset, $> doc_list_items($> doc_value(D, depr_ui:depreciation_assets)))
	->	true
	;	throw_string('depreciation: assets processing failed')),

	% events sheet is optional
	(	doc_value(D, depr_ui:depreciation_events, Events)
	->	(	maplist(process_depreciation_event, $> doc_list_items(Events))
		->	true
		;	throw_string('depreciation: events processing failed'))
	;	true
	),

	(	maplist(process_depreciation_query, $> doc_list_items($> doc_value(D, depr_ui:depreciation_queries)))
	->	true
	;	throw_string('depreciation: queries processing failed')).
```
is translated into:
```
user:process_request_depreciation_new :-
    request_data(A),
    doc_value(A,
              'https://rdf.lodgeit.net.au/v1/calcs/depr/ui#depreciation_queries',
              _),
    doc_value(A,
              'https://rdf.lodgeit.net.au/v1/calcs/depr/ui#depreciation_assets',
              B),
    doc_list_items(B, C),
    (   '__aux_maplist/2_process_depreciation_asset+0'(C)
    ->  true
    ;   throw_string('depreciation: assets processing failed')
    ),
    doc_list_items(D, E),
    (   doc_value(A,
                  'https://rdf.lodgeit.net.au/v1/calcs/depr/ui#depreciation_events',
                  D)
    ->  (   '__aux_maplist/2_process_depreciation_event+0'(E)
        ->  true
        ;   throw_string('depreciation: events processing failed')
        )
    ;   true
    ),
    doc_value(A,
              'https://rdf.lodgeit.net.au/v1/calcs/depr/ui#depreciation_queries',
              F),
    doc_list_items(F, G),
    (   '__aux_maplist/2_process_depreciation_query+0'(G)
    ->  true
    ;   throw_string('depreciation: queries processing failed')
    ).
```
note how the second and third calls to `doc_value` are put to the beginning. In the first case, it works well, because the `    doc_value(A,
              'https://rdf.lodgeit.net.au/v1/calcs/depr/ui#depreciation_assets',
              B),` does not depend on the subsequent `     doc_list_items(B, C), `. 

But in the second case, the `    doc_list_items(D, E),` depends on the `
    (   doc_value(A,
                  'https://rdf.lodgeit.net.au/v1/calcs/depr/ui#depreciation_events',
                  D)
`, which is called after it. 

Other problems show around swipl dicts.

**Comment by awto** [comment]
thanks for the report, do you mean the expansion should be kept inside the first argument of the arrows there?

**Comment by koo5** [comment]
hi. Yes, it should be like: (doc_list_items..,__aux_maplist...).
I didn't expect any replies here really, pleasant surprise! I use fnotation a lot, but in some places it keeps biting me:)

**Comment by awto** [comment]
Now it looks the nearest ',' operator or a body, this seems to be wrong. So there are two ways, either add other types of boundaries, (e.g. '->', ';' etc), or add it them to the top '$>'. The first would require listing all such boundary operators, while the second might not work if there is an intended term construction we don't mean to unfold. 

I think I'll implement the second option (however I may only have time for this is a couple of weeks). Maybe you may have any other suggestion?

**Comment by awto** [comment]
@koo5 I've just published a version with meta_predicate based boundary, could you please check if this solves the problem? It is v1.0.0.
